const GET_RESTAURANT_DATA = 'GET_RESTAURANT_DATA';
const GET_RESTAURANT_DATA_SUCCESS = 'GET_RESTAURANT_DATA_SUCCESS';
const GET_RESTAURANT_DATA_FAILURE = 'GET_RESTAURANT_DATA_FAILURE';
const NEW_RESTAURANT_SELECTED = 'NEW_RESTAURANT_SELECTED';

export {
  GET_RESTAURANT_DATA,
  GET_RESTAURANT_DATA_SUCCESS,
  GET_RESTAURANT_DATA_FAILURE,
  NEW_RESTAURANT_SELECTED,
}
